# Generated by Django 5.2.4 on 2025-07-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='department',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
