# Generated by Django 5.2.4 on 2025-07-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_timesheet_department_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='week',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
