# Generated by Django 5.2.4 on 2025-07-10 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_timesheet_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='week',
        ),
    ]
