# Generated by Django 3.2.25 on 2025-07-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20250713_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmenthead',
            name='sub_department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
