# Generated by Django 3.2.25 on 2025-07-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_departmenthead_sub_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='allocated_post',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='sub_department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
