# Generated by Django 3.2.25 on 2025-07-14 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_duty'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocatedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('sub_department', models.CharField(blank=True, max_length=100, null=True)),
                ('post_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.departmenthead')),
            ],
            options={
                'ordering': ['post_name'],
                'unique_together': {('department', 'sub_department', 'post_name')},
            },
        ),
        migrations.CreateModel(
            name='PostDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duties', to='tracker.allocatedpost')),
            ],
            options={
                'verbose_name_plural': 'Post Duties',
                'ordering': ['duty_name'],
            },
        ),
        migrations.DeleteModel(
            name='Duty',
        ),
    ]
