# Generated by Django 3.2.25 on 2025-07-14 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_auto_20250714_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='allocated_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.allocatedpost'),
        ),
    ]
