# Generated by Django 3.2.25 on 2025-07-14 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_alter_employee_allocated_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='category',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='week',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='work_description',
        ),
        migrations.CreateModel(
            name='TimesheetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.postduty')),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tracker.timesheet')),
            ],
        ),
    ]
