# Generated by Django 5.2.4 on 2025-07-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_auto_20250714_1619'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='allocatedpost',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='allocatedpost',
            name='post_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='postduty',
            unique_together={('post', 'duty_name')},
        ),
        migrations.RemoveField(
            model_name='allocatedpost',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='allocatedpost',
            name='department',
        ),
        migrations.RemoveField(
            model_name='allocatedpost',
            name='sub_department',
        ),
    ]
