# Generated by Django 5.2.4 on 2025-07-30 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_alter_allocatedpost_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postduty',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='allocatedpost',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.departmenthead'),
        ),
        migrations.AddField(
            model_name='allocatedpost',
            name='department',
            field=models.CharField(default='ADM', max_length=100),
        ),
        migrations.AddField(
            model_name='allocatedpost',
            name='sub_department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='allocatedpost',
            name='post_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='allocatedpost',
            unique_together={('department', 'sub_department', 'post_name')},
        ),
    ]
