# Generated by Django 5.2.4 on 2025-07-30 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_alter_postduty_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentPostName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DutyName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='allocatedpost',
            name='post_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.departmentpostname'),
        ),
        migrations.AlterField(
            model_name='postduty',
            name='duty_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.dutyname'),
        ),
    ]
