# Generated by Django 5.2.4 on 2025-07-30 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_departmentpostname_dutyname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duty_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.dutyname')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duties', to='tracker.employee')),
            ],
            options={
                'verbose_name_plural': 'Employee Duties',
                'ordering': ['duty_name'],
            },
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='duty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.employeeduty'),
        ),
        migrations.DeleteModel(
            name='PostDuty',
        ),
    ]
